### ISSUE TITLE
Add option to dump system to xml

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#260] opened 2023-02-16 14:13 UTC
Based on call with Joe Bluck.

**Comment by richardjgowers** [comment] 2023-02-20 10:15
probably TOML not YAML, but yes

https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell

**Comment by IAlibay** [comment] 2023-02-20 13:19
Actually I was being distracted here, I meant XML 😅

**Comment by richardjgowers** [comment] 2023-02-23 10:08
duplicate of #234

**Closed by richardjgowers** 2023-02-23 10:08 UTC
Labels: openmm_rbfe
