### ISSUE TITLE
FireMinimizationIntegrator fails on CPU platforms

### ISSUE THREAD

**Issue by MKCarter** [OpenFreeEnergy/openfe#253] opened 2023-02-03 08:05 UTC
Hey,

I have been playing around with the tutorial [notebook](https://mybinder.org/v2/gh/OpenFreeEnergy/ExampleNotebooks/HEAD?labpath=openmm-rbfe%2FOpenFE_showcase_1_RBFE_of_T4lysozyme.ipynb) - but I see that it calls `openeye_wrapper.py `for molecule to SMILES conversion. As a non oechem license holder, I was just wondering if you plan to add an rdkit version to the code any time soon? 

Thanks,
Mike

**Comment by richardjgowers** [comment] 2023-02-03 10:05
Hi Mike

We don't actually use OEChem for this (or anywhere in our code base).  Everything we're doing is based on rdkit, I think the only oechem things we have are `to_oechem()` methods to generate an OEMol.  

Regardings SMILES, if you've got a Component, you can just call `.smiles` and it will use `Chem.MolToSmiles` (from here: 
https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/components/explicitmoleculecomponent.py#L80)

**Comment by dwhswenson** [comment] 2023-02-07 21:00
We've now had another report of this issue (by email): @MKCarter, could you tell us the versions of `openmmforcefields` and of `openff-toolkit` that you have installed? It seems to be coming from one of those.

**Comment by dwhswenson** [comment] 2023-02-08 16:26
This is a bug in openff-toolkit 0.11.2. It should be fixed by upgrading to openff-toolkit 0.11.4 (actually, I think 0.11.3 will fix as well). Issue described here: https://github.com/openforcefield/openff-toolkit/issues/1435; fixed here: https://github.com/openforcefield/openff-toolkit/pull/1436

**Comment by richardjgowers** [comment] 2023-02-10 16:48
@MKCarter we've pushed some new conda-forge packages that resolve this.  Running `conda update -c conda-forge openfe` should resolve this

**Comment by MKCarter** [comment] 2023-02-13 01:10
@richardjgowers - That did fix the issue. However, I now see another issue with locating the `openff-2.0.0off.xml` file see the error below:

`---------------------------------------------------------------------------
DefinitionSyntaxError                     Traceback (most recent call last)
File ~/.conda/envs/openfe/lib/python3.10/site-packages/openmmforcefields/generators/template_generators.py:1278, in SMIRNOFFTemplateGenerator.__init__(self, molecules, cache, forcefield)
   1277         filename += '.offxml'
-> 1278     self._smirnoff_forcefield = openff.toolkit.typing.engines.smirnoff.ForceField(filename)
   1279 except Exception as e:

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py:307, in ForceField.__init__(self, aromaticity_model, parameter_handler_classes, parameter_io_handler_classes, disable_version_check, allow_cosmetic_attributes, load_plugins, *sources)
    306 # Parse all sources containing SMIRNOFF parameter definitions
--> 307 self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py:768, in ForceField.parse_sources(self, sources, allow_cosmetic_attributes)
    767 smirnoff_data = self.parse_smirnoff_from_source(source)
--> 768 self._load_smirnoff_data(
    769     smirnoff_data, allow_cosmetic_attributes=allow_cosmetic_attributes
    770 )

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py:876, in ForceField._load_smirnoff_data(self, smirnoff_data, allow_cosmetic_attributes)
    875 # Go through the whole SMIRNOFF data structure, trying to convert all strings to Quantity
--> 876 smirnoff_data = convert_all_strings_to_quantity(smirnoff_data)
    878 # Go through the subsections, delegating each to the proper ParameterHandler
    879 
    880 # Define keys which are expected from the spec, but are not parameter sections

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:233, in convert_all_strings_to_quantity(smirnoff_data)
    232 for key, value in smirnoff_data.items():
--> 233     smirnoff_data[key] = convert_all_strings_to_quantity(value)
    234 obj_to_return = smirnoff_data

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:233, in convert_all_strings_to_quantity(smirnoff_data)
    232 for key, value in smirnoff_data.items():
--> 233     smirnoff_data[key] = convert_all_strings_to_quantity(value)
    234 obj_to_return = smirnoff_data

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:233, in convert_all_strings_to_quantity(smirnoff_data)
    232 for key, value in smirnoff_data.items():
--> 233     smirnoff_data[key] = convert_all_strings_to_quantity(value)
    234 obj_to_return = smirnoff_data

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:238, in convert_all_strings_to_quantity(smirnoff_data)
    237 for index, item in enumerate(smirnoff_data):
--> 238     smirnoff_data[index] = convert_all_strings_to_quantity(item)
    239 obj_to_return = smirnoff_data

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:233, in convert_all_strings_to_quantity(smirnoff_data)
    232 for key, value in smirnoff_data.items():
--> 233     smirnoff_data[key] = convert_all_strings_to_quantity(value)
    234 obj_to_return = smirnoff_data

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:246, in convert_all_strings_to_quantity(smirnoff_data)
    245 try:
--> 246     obj_to_return = object_to_quantity(smirnoff_data)
    247 except (AttributeError, TypeError, SyntaxError):

File ~/.conda/envs/openfe/lib/python3.10/functools.py:889, in singledispatch.<locals>.wrapper(*args, **kw)
    886     raise TypeError(f'{funcname} requires at least '
    887                     '1 positional argument')
--> 889 return dispatch(args[0].__class__)(*args, **kw)

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:318, in _(obj)
    317 try:
--> 318     return string_to_quantity(obj)
    319 except pint.errors.UndefinedUnitError:

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openff/toolkit/utils/utils.py:200, in string_to_quantity(quantity_string)
    199 try:
--> 200     quantity = unit.Quantity(quantity_string)
    201 except (TokenError, UndefinedUnitError):

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/facets/plain/quantity.py:209, in PlainQuantity.__new__(cls, value, units)
    208 ureg = SharedRegistryObject.__new__(cls)._REGISTRY
--> 209 inst = ureg.parse_expression(value)
    210 return cls.__new__(cls, inst)

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/facets/plain/registry.py:1255, in PlainRegistry.parse_expression(self, input_string, case_sensitive, use_decimal, **values)
   1253 gen = tokenizer(input_string)
-> 1255 return build_eval_tree(gen).evaluate(
   1256     lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
   1257 )

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/pint_eval.py:114, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    113     raise DefinitionSyntaxError('missing binary operator "%s"' % op_text)
--> 114 left = self.left.evaluate(define_op, bin_op, un_op)
    115 return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/pint_eval.py:114, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    113     raise DefinitionSyntaxError('missing binary operator "%s"' % op_text)
--> 114 left = self.left.evaluate(define_op, bin_op, un_op)
    115 return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))

    [... skipping similar frames: EvalTreeNode.evaluate at line 114 (4 times)]

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/pint_eval.py:114, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    113     raise DefinitionSyntaxError('missing binary operator "%s"' % op_text)
--> 114 left = self.left.evaluate(define_op, bin_op, un_op)
    115 return bin_op[op_text](left, self.right.evaluate(define_op, bin_op, un_op))

File ~/.conda/envs/openfe/lib/python3.10/site-packages/pint/pint_eval.py:120, in EvalTreeNode.evaluate(self, define_op, bin_op, un_op)
    119 if op_text not in un_op:
--> 120     raise DefinitionSyntaxError('missing unary operator "%s"' % op_text)
    121 return un_op[op_text](self.left.evaluate(define_op, bin_op, un_op))

DefinitionSyntaxError: missing unary operator "*"

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[36], line 4
      1 # solvent dry-run
      2 solvent_unit = list(solvent_dag.protocol_units)[0]
----> 4 solvent_unit.run(dry=True, verbose=True)

File ~/DD_tools/openfe/openfe/protocols/openmm_rbfe/equil_rbfe_methods.py:840, in RelativeLigandTransformUnit.run(self, dry, verbose, basepath)
    837 stateB_openff_ligand = stateB['ligand'].to_openff()
    839 #  1. Get smirnoff template generators
--> 840 smirnoff_stateA = SMIRNOFFTemplateGenerator(
    841     forcefield=settings.topology_settings.forcefield['ligand'],
    842     molecules=[stateA_openff_ligand],
    843 )
    845 smirnoff_stateB = SMIRNOFFTemplateGenerator(
    846     forcefield=settings.topology_settings.forcefield['ligand'],
    847     molecules=[stateB_openff_ligand],
    848 )
    850 # 2. Create forece fields and register them
    851 #  a. state A

File ~/.conda/envs/openfe/lib/python3.10/site-packages/openmmforcefields/generators/template_generators.py:1281, in SMIRNOFFTemplateGenerator.__init__(self, molecules, cache, forcefield)
   1279 except Exception as e:
   1280     _logger.error(e)
-> 1281     raise ValueError(f"Can't find specified SMIRNOFF force field ({forcefield}) in install paths")
   1283 # Delete constraints, if present
   1284 if 'Constraints' in self._smirnoff_forcefield._parameter_handlers:

ValueError: Can't find specified SMIRNOFF force field (openff-2.0.0.offxml) in install paths`

Any suggestions on how to remedy this?

**Comment by richardjgowers** [comment] 2023-02-24 09:09
@MKCarter this might be because you haven't installed them, can you check the debug here? https://github.com/openmm/openmmforcefields#using-the-open-force-field-initiative-smirnoff-small-molecule-force-fields

Or more generally, how have you installed your environment so far?

**Comment by MKCarter** [comment] 2023-02-25 02:44
Hi @richardjgowers 

So I have installed openfe using conda - `conda install -c conda-forge openfe`

I have checked and the libraries are definitely installed as part of the package:
`print(SMIRNOFFTemplateGenerator.INSTALLED_FORCEFIELDS)`

Gives me this output:

`['smirnoff99Frosst-1.0.2', 'smirnoff99Frosst-1.0.0', 'smirnoff99Frosst-1.1.0', 'smirnoff99Frosst-1.0.4', 'smirnoff99Frosst-1.0.8', 'smirnoff99Frosst-1.0.6', 'smirnoff99Frosst-1.0.3', 'smirnoff99Frosst-1.0.1', 'smirnoff99Frosst-1.0.5', 'smirnoff99Frosst-1.0.9', 'smirnoff99Frosst-1.0.7', 'ff14sb_off_impropers_0.0.2', 'ff14sb_off_impropers_0.0.1', 'ff14sb_off_impropers_0.0.3', 'openff-1.0.1', 'openff-1.1.1', 'openff-1.0.0-RC1', 'openff-1.2.0', 'openff-1.3.0', 'openff-2.0.0-rc.2', 'openff-2.0.0', 'openff-1.1.0', 'openff-1.0.0', 'openff-1.0.0-RC2', 'openff-1.3.1', 'openff-1.2.1', 'openff-1.3.1-alpha.1', 'openff-2.0.0-rc.1']`

So it looks like it just can't find the installed ff's - is there anywhere that I need to specify the path? I know where the path is to the files - on my setup it is located `conda/envs/openfe/lib/python3.10/site-packages/openmmforcefields/ffxml/offxml`

Interestingly if I try to load the openff forcefield directly it seems to find it OK.

`forcefield = ForceField('offxml/openff-2.0.0.offxml')`

Runs and loads the forcefield, but running this causes the same error message as above:
`smirnoff = SMIRNOFFTemplateGenerator(molecules=molecule)`

Many thanks

**Comment by MKCarter** [comment] 2023-02-25 08:56
So I re-installed the entire openfe packages, now when trying to run:
```
from openfe.setup import SmallMoleculeComponent

# Create and SDF supplier
# Extract the contents of the sdf file and visualise it
ligands_sdf = Chem.SDMolSupplier('inputs/ligands.sdf', removeHs=False)

# Now pass these to form a list of Molecules
ligand_mols = [SmallMoleculeComponent(sdf) for sdf in ligands_sdf]
```

I am seeing that the `SmallMoleculeComponent` is now no longer part of the openfe.setup...

**Comment by IAlibay** [comment] 2023-03-17 14:25
Sorry about the long delay for responses here, could you provide a full list of packages installed in your environment @MKCarter ? This definitely shouldn't be happening.

**Comment by IAlibay** [comment] 2023-04-17 16:19
Hi @MKCarter - Just wanted to catch up here. We've done lots of changes with the v0.7, could you maybe retry with a fresh install?

**Comment by IAlibay** [comment] 2023-04-18 13:41
@MKCarter that is indeed strange, is this a publicly available version of the JNK1 set? I can try to get it running on my end.

The protocol _should_ be sufficiently minimizing the system (both with a short CPU run to avoid NaNs and then GPU if you're using it). If the input is really bad it won't resolve that, but hopefully JNK1 should be a well defined input already.

**Comment by MKCarter** [comment] 2023-04-18 13:58
Hi @IAlibay - Yeah, this is the JNK1 example that is found on the openfreenergy [binder](http://try.openfree.energy/) example notebooks. I also obtain the same NaN errors for the T4-Lysosyme example. The errors appear running via the example jupyter-notebooks on binder and also locally on my machine. I agree, this is a bit odd.

**Comment by IAlibay** [comment] 2023-04-18 14:02
Thanks for confirming @MKCarter - I'll try to see if I can replicate the issue on my end. Are you able to let us know what type of machine you're running this on? Specifically any GPU type you're using might be of help here (e.g. we've really not validated this on OpenCL).

**Comment by IAlibay** [comment] 2023-04-18 14:41
Ah I wonder the M1 might be the issue - @richardjgowers or @dwhswenson can you reproduce this on your machines?

**Comment by dwhswenson** [comment] 2023-04-18 17:39
It's also happening in Binder, so the problem is not an issue of M1. It may be an issue of not having CUDA around, though.

Working on the CLI tutorial (RHFE) in Binder I get a similar behavior (not sure why this is such a different code path, but same error on minimization):

```pytb
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/gufe/protocols/protocolunit.py", line 286, in execute
    outputs = self._execute(context, **inputs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openfe/protocols/openmm_rfe/equil_rfe_methods.py", line 725, in _execute
    outputs = self.run(basepath=ctx.shared)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openfe/protocols/openmm_rfe/equil_rfe_methods.py", line 671, in run
    sampler.setup(
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openfe/protocols/openmm_rfe/_rfe_utils/multistate.py", line 123, in setup
    minimize(compound_thermostate_copy, sampler_state,
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openfe/protocols/openmm_rfe/_rfe_utils/multistate.py", line 293, in minimize
    openmm.LocalEnergyMinimizer.minimize(
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openmm/openmm.py", line 4388, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
```

Also I think @MKCarter's trace may be from the showcase notebook. I'm seeing something similar there.

**Comment by dwhswenson** [comment] 2023-04-18 17:48
Got it: Problem is OpenMMTools and OpenMM aren't communicating well. The exception reads: `Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan`

OpenMMTools is checking against a specific string (which is no longer valid) to handle this error case:

```python
        except Exception as e:
            if str(e) == 'Particle coordinate is nan':
                logger.debug('NaN encountered in FIRE minimizer; falling back to L-BFGS after resetting positions')
                sampler_state.apply_to_context(context)
                openmm.LocalEnergyMinimizer.minimize(context, tolerance, max_iterations)
            else:
                raise e
```
(https://github.com/choderalab/openmmtools/blob/47807bba462a7ac91a7da3075587629bb647fc6a/openmmtools/multistate/multistatesampler.py#L1381-L1387)

Opened a PR in OpenMMTools to fix. Not sure what else we can do from our end? (Pin OpenMM version to whenever the text changed?)

**Comment by IAlibay** [comment] 2023-04-18 17:56
We do a pre minimisation ahead of using the FIRE minimizer, if we're hitting a NaN there something went wrong

**Comment by MKCarter** [comment] 2023-04-18 19:59
@dwhswenson - yeah, these examples are all from the showcase notebooks. I can confirm these errors are reproducible on my local M1 Mac and binder. Great to hear you have the root cause identified! Thank you both for looking into this!

**Comment by IAlibay** [comment] 2023-04-18 20:00
To follow-up here, @dwhswenson's observation is correct, although it seems like we were relying on that error catching to hide a deeper issue with the OpenMMTools FIREMinimizationIntegrator (see: https://github.com/choderalab/openmmtools/issues/686).

Looks like a new release of OpenMMTools will be out soon that will include @dwhswenson's fix. For now that _should_ be ok (since the default is to just use LocalEnergyMinimizer). Longer term it looks like we'll be ditching the FIRE minimizer altogether.

**Comment by MKCarter** [comment] 2023-04-21 14:18
@IAlibay - I can confirm that updating `openmmtools` and `openfe` appears to have solved the issue. Many thanks for all your help with this.

**Comment by IAlibay** [comment] 2023-04-21 14:21
That's amazing to hear @MKCarter !

I'm going to close this issue, but do please keep us updated on any further issues (or positive outcomes if you're willing to share!). We're very keen to get this from development code to fully working in folk's hands.

**Closed by IAlibay** 2023-04-21 14:21 UTC

**Comment by MKCarter** [comment] 2023-04-21 20:56
Of course, anything that I can share, I will. This is a really cool initiative and I am looking forward to see how it develops 👍 - if I can help in anyway that is a bonus.
