### ISSUE TITLE
[OpenMM RFE] clarify `scratch_basepath`

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#346] opened 2023-04-14 17:38 UTC
The `run` method has both `scratch_basepath` and `shared_basepath`. From the look of things, the former just doesn't get used by anything? We should clarify this to users and look at whether or not it's actually worth having around?

**Comment by richardjgowers** [comment] 2024-01-19 13:53
this seems like a duplicate of #292

**Closed by richardjgowers** 2024-01-19 13:53 UTC
