### ISSUE TITLE
[docs] Settings docs

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#297] opened 2023-04-05 10:50 UTC
- [ ] Make pydantic autodocs work & settings exposed (requires #267)
- [ ] Have user docs on settings

**Comment by richardjgowers** [comment] 2023-04-06 16:26
This sounds like it's detailing the RHTP settings right?  The settings system in general will be covered in #302 right?

**Comment by richardjgowers** [comment] 2023-04-06 16:29
So is maybe a duplicate of #296 ?

**Comment by IAlibay** [comment] 2023-04-06 17:11
So ideally settings are linked to but not directly in the docstring for RHTP?

**Comment by richardjgowers** [comment] 2024-03-12 11:47
this PR seems to have hit this: https://github.com/OpenFreeEnergy/openfe/pull/766

This page and similar seem to be doing the job https://docs.openfree.energy/en/latest/reference/api/openmm_rfe.html

**Closed by richardjgowers** 2024-03-12 11:47 UTC
Labels: documentation, cookbook, 1.0docdrive
