### ISSUE TITLE
Trouble reconciling results from json with openfe gather --report raw

### ISSUE THREAD

**Issue by arjun-nufc** [OpenFreeEnergy/openfe#925] opened 2024-08-28 14:06 UTC
Hi, I am seeing different results from `openfe gather --report raw` and the estimate found in the `results.json` file.  

This is what i get from `openfe gather --report raw`:

```
leg	ligand_i	ligand_j	DG(i->j) (kcal/mol)	MBAR uncertainty (kcal/mol)
complex	lig1	lig2	0.10	0.06
solvent	lig1	lig2	-0.68	0.06
```

This is what i get from the complex leg when reading in the results.json file:
```
>>>f = open("Transformation-b10b89ea4409926d4462e859b88a4f30_results.json", 'r')
>>>d = json.loads(f.read())
>>>d["estimate"]
{'magnitude': -0.2931549270309974, 'unit': 'kilocalorie_per_mole', ':is_custom:': True, 'pint_unit_registry': 'openff_units'}
```

should the numbers from the complex leg of openfe gather --report raw match with that of the value for "estimate" from the json?  If not, can someone explain to me what these two numbers represent ?  

Thanks in advance,
Arjun

**Comment by arjun-nufc** [comment] 2024-09-03 19:27
@IAlibay - any thoughts?

**Comment by jthorton** [comment] 2024-10-18 14:18
Is this related to https://github.com/OpenFreeEnergy/openfe/pull/884?

**Comment by atravitz** [comment] 2024-10-22 16:49
Hi @arjun-nufc, thanks for finding this. We believe might now be fixed on the `main` branch. Could you let us know if this solves your issue?

**Comment by IAlibay** [comment] 2024-10-23 11:24
To provide a bit more background. We believe that the the issue was, as pointed out in #884, that only a single repeat was being extracted from the results JSON files when calling the `--report raw` option, rather than all the individual repeats.

The intended behaviour, and one that should have been fixed in the current develop version of `openfe` is that `--report raw` should return the estimate for each repeat.

Note: The "estimate" entry in the JSON file is actually the average of the all the individual repeat estimates, which is why you are seeing a difference.

**Closed** 2024-11-12 14:35 UTC
